sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_00afeeec2713_key -iv $encrypted_00afeeec2713_iv -in multi-k8s-414117-b411fbfb804b.json.enc -out multi-k8s-414117-b411fbfb804b.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-414117-b411fbfb804b.json
  - gcloud config set project multi-k8s-414117
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t mkirby1974/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkirby1974/multi-client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
